/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ConversionTransformer from '#transformers/conversion_transformer'
import type CurrencyTransformer from '#transformers/currency_transformer'
import type RateSetTransformer from '#transformers/rate_set_transformer'
import type TimeseriesRateSetTransformer from '#transformers/timeseries_rate_set_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Conversion = InferData<ConversionTransformer>
  export namespace Conversion {
    export type Variants = InferVariants<ConversionTransformer>
  }
  export type Currency = InferData<CurrencyTransformer>
  export namespace Currency {
    export type Variants = InferVariants<CurrencyTransformer>
  }
  export type RateSet = InferData<RateSetTransformer>
  export namespace RateSet {
    export type Variants = InferVariants<RateSetTransformer>
  }
  export type TimeseriesRateSet = InferData<TimeseriesRateSetTransformer>
  export namespace TimeseriesRateSet {
    export type Variants = InferVariants<TimeseriesRateSetTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
