/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CurrencyTransformer from '#transformers/currency_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Currency = InferData<CurrencyTransformer>
  export namespace Currency {
    export type Variants = InferVariants<CurrencyTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
