import { configApp } from '@adonisjs/eslint-config'

export default configApp({
  // Regenerated by `node ace migration:run`, so formatting fixes would not stick.
  ignores: ['database/schema.ts'],
})
