/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CurrencySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'firstDate', 'isActive', 'lastDate', 'name', 'updatedAt'] as const
  $columns = CurrencySchema.$columns
  @column({ isPrimary: true })
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare firstDate: DateTime | null
  @column()
  declare isActive: boolean
  @column.date()
  declare lastDate: DateTime | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateSchema extends BaseModel {
  static $columns = ['createdAt', 'currency', 'date', 'id', 'rate', 'updatedAt'] as const
  $columns = RateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rate: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SyncRunSchema extends BaseModel {
  static $columns = ['error', 'finishedAt', 'id', 'latestDate', 'rowsUpserted', 'source', 'startedAt', 'status'] as const
  $columns = SyncRunSchema.$columns
  @column()
  declare error: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare latestDate: DateTime | null
  @column()
  declare rowsUpserted: number | null
  @column()
  declare source: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
